# Eisen und Zink in Salat  {#sec-app-fe-zn}

*Letzte Änderung am `r format(fs::file_info("example-analysis-02.qmd")$modification_time, '%d. %B %Y um %H:%M:%S')`*

::: callout-note
## Genutzte R Pakete
```{r echo = TRUE}
#| message: false
#| warning: false
pacman::p_load(tidyverse, readxl, parameters,
               effectsize, magrittr, multcomp,
               multcompView, rcompanion, rstatix,
               emmeans, see, performance, fs,
               janitor, broom, scales, knitr,
               conflicted)
## resolve some conflicts with same function naming
conflicts_prefer(dplyr::select)
conflicts_prefer(dplyr::filter)
conflicts_prefer(effectsize::eta_squared)
conflicts_prefer(magrittr::set_names)
```
:::

## Daten einlesen

```{r}
#| message: false

data_tbl <- read_csv2("data/fe_zn_salad.csv") %>% 
  clean_names() %>% 
  fill(eisendungeform) %>% 
  mutate(eisendungeform = str_replace_all(eisendungeform, "\u0096 7 ", ""),
         versuchsgruppe = str_c(eisendungeform, "_", eisendungung)) %>% 
  pivot_longer(cols = zn_blanchiert:fe_ungewaschen,
               names_to = "outcome",
               values_to = "rsp")

```

## Daten auswerten

```{r}

nested_tbl <- data_tbl %>% 
  select(versuchsgruppe, outcome, rsp) %>% 
  group_by(outcome) %>% 
  nest() 

aov_res <- nested_tbl %>% 
  mutate(model = map(data, ~lm(rsp ~ versuchsgruppe, data = .x))) %>% 
  mutate(anova = map(model, anova)) %>% 
  mutate(parameter = map(anova, model_parameters)) %>% 
  select(outcome, parameter) %>% 
  unnest(parameter) %>% 
  clean_names() %>% 
  mutate(p = pvalue(p)) %>% 
  filter(parameter != "Residuals") %>% 
  select(outcome, parameter, p)

aov_res %>% 
  kable(align = "c", "pipe")

emm_tbl <- nested_tbl %>% 
  mutate(model = map(data, ~lm(rsp ~ versuchsgruppe, data = .x))) %>% 
  mutate(emm = map(model, emmeans, ~versuchsgruppe)) %>% 
  mutate(contrast = map(emm, contrast, method = "pairwise", 
                        adjust = "none")) %>% 
  mutate(cld = map(emm, cld, Letters = letters, adjust = "none"))
  
emm_tbl %>% 
  mutate(contrast = map(contrast, as_tibble)) %>% 
  unnest(contrast) %>% 
  select(outcome, contrast, p.value) %>% 
  mutate(p.value = pvalue(p.value)) %>% 
  print(n = 10)

emm_tbl %>% 
  mutate(cld = map(cld, arrange, versuchsgruppe)) %>% 
  unnest(cld) %>% 
  select(outcome, versuchsgruppe, .group) %>% 
  print(n = Inf)

gg_func <- function(data){
  data %>% 
    mutate(.group = str_replace_all(.group, "\\s", "")) %>% 
    ggplot(aes(versuchsgruppe, emmean)) +
    theme_minimal() +
    geom_bar(stat = "identity")  +
    geom_errorbar(aes(ymin = emmean - SE, ymax = emmean + SE), width = 0.2) +
    geom_text(aes(label = .group, y = (emmean + SE) + (0.05 * (emmean + SE)))) +
    theme(axis.text.x = element_text(angle = -45, hjust = 0))
}

```



```{r}
#| echo: false
#| message: false
#| warning: false

gg_func <- function(data){
  data %>% 
    mutate(.group = str_replace_all(.group, "\\s", "")) %>% 
    ggplot(aes(versuchsgruppe, emmean)) +
    theme_minimal() +
    labs(x = "", y = "") +
    geom_bar(stat = "identity")  +
    scale_x_discrete(expand = expansion(add = c(NA, 1))) +
    geom_errorbar(aes(ymin = emmean - SE, ymax = emmean + SE), width = 0.2) +
    geom_text(aes(label = .group, y = (emmean + SE) + (0.02 * (emmean + SE))),
              vjust = 0) +
    theme(axis.text.x = element_text(angle = -45, hjust = 0))
}

```

[Plot math expression](https://stat.ethz.ch/R-manual/R-patched/library/grDevices/html/plotmath.html)

```{r}
#| echo: true
#| message: false
#| warning: false
#| fig-align: center
#| fig-height: 5
#| fig-width: 6
#| label: fig-pois-03
#| fig-cap: "Barplots der Mittelwerte und Standardfehler für die vier Outcomes."
#| fig-subcap: 
#|   - "zn_blanchiert"
#|   - "zn_ungewaschen"
#|   - "fe_blanchiert"
#|   - "fe_ungewaschen"
#| layout-ncol: 2 
#| column: page

emm_tbl %>% 
  mutate(gg = map(cld, gg_func)) %>% 
  pluck("gg", 1) +
  labs(x = expression(Eisendüngeform~und~-höhe~"[kg ha]"^-1),
       y = expression(Zn-Gehalt~"["~mg%.%(100~g~FM)^-1~"]"))

emm_tbl %>% 
  mutate(gg = map(cld, gg_func)) %>% 
  pluck("gg", 2) +
  labs(x = expression(Eisendüngeform~und~-höhe~"[kg ha]"^-1),
       y = expression(Zn-Gehalt~"["~mg%.%(kg~TM)^-1~"]"))

emm_tbl %>% 
  mutate(gg = map(cld, gg_func)) %>% 
  pluck("gg", 3) +
  labs(x = expression(Eisendüngeform~und~-höhe~"[kg ha]"^-1),
       y = expression(Fe-Gehalt~"["~mg%.%(100~g~FM)^-1~"]"))

emm_tbl %>% 
  mutate(gg = map(cld, gg_func)) %>% 
  pluck("gg", 4) +
  labs(x = expression(Eisendüngeform~und~-höhe~"[kg ha]"^-1),
       y = expression(Fe-Gehalt~"["~mg%.%(kg~TM)^-1~"]"))
```
