# Steuerung der vegetativen Entwicklung krautiger Pflanzen (44B0608) {#sec-app-basilikum}

*Version vom `r format(Sys.time(), '%B %d, %Y um %H:%M:%S')`*

Wir wollen folgende R Pakete in diesem Kapitel nutzen.

```{r echo = TRUE}
#| message: false
#| warning: false
pacman::p_load(tidyverse, readxl, parameters,
               effectsize, magrittr, multcomp,
               multcompView, rcompanion, rstatix,
               emmeans, see,
               conflicted)
## resolve some conflicts with same function naming
conflicts_prefer(dplyr::select)
conflicts_prefer(dplyr::filter)
conflicts_prefer(effectsize::eta_squared)
```

Es geht hier um das Modul [Steuerung der vegetativen Entwicklung krautiger Pflanzen (44B0608)](https://www.hs-osnabrueck.de/module/44b0608/)


```{r}
#| message: false
#| warning: false

basi_tbl <- read_excel("data/keimversuch_basilikum.xlsx") %>% 
  mutate(versuchsgruppe = as_factor(versuchsgruppe))

## Ist das Outcome ann채hrend normalverteilt
## -> ja, ANOVA
## -> nein, Sie unten

ggplot(basi_tbl, aes(versuchsgruppe, frischmasse)) +
  theme_bw() +
  geom_point()

basi_tbl %>%
  group_by(versuchsgruppe) %>%
  shapiro_test(frischmasse)


## Wir nehmen an, dass es sich bei Frischmasse um einen ann채hrend
## normalverteilten Endpunkt handelt.

fit <- lm(frischmasse ~ versuchsgruppe, data = basi_tbl)

fit %>% 
  anova() %>% 
  parameters()

fit %>% 
  eta_squared()

## posthoc Test durchf체hren. 
## Welcher paarweise Unterschied ist signifikant?

## alle Varianzen in allen Gruppen sind gleich
basi_tbl %$%
  pairwise.t.test(frischmasse, versuchsgruppe)

## alle Varianzen unterscheiden sich
basi_tbl %$%
  pairwise.t.test(frischmasse, versuchsgruppe,
                  pool.sd = FALSE)

## Soll ich f체r multiple Vergleiche adjustieren?
## -> nein!

basi_tbl %$%
  pairwise.t.test(frischmasse, versuchsgruppe,
                  pool.sd = FALSE, p.adjust.method = "none")

## -> ja

basi_tbl %$%
  pairwise.t.test(frischmasse, versuchsgruppe,
                  pool.sd = FALSE, 
                  p.adjust.method = "bonferroni")
## Die p-Werte sind nach Bonferroni adjustiert



basi_tbl %$%
  pairwise.t.test(frischmasse, versuchsgruppe,
                  pool.sd = FALSE, 
                  p.adjust.method = "bonferroni") %>% 
  extract2("p.value") %>% 
  fullPTable() %>% 
  multcompLetters()


## Barplot mit compact letter display und abspeichern

stat_tbl <- basi_tbl %>% 
  group_by(versuchsgruppe) %>% 
  summarise(mean = mean(frischmasse),
            sd = sd(frischmasse),
            se = sd/sqrt(n()))

ggplot(stat_tbl, aes(x = versuchsgruppe, y = mean, 
                     fill = versuchsgruppe)) + 
  theme_bw() +
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin = mean-sd, ymax = mean+sd),
                width = 0.2) +
  labs(x = "Versuchsgruppe", y = "Frischmasse in [g]") +
  theme(legend.position = "none") +
  scale_fill_okabeito() +
  annotate("text", 
           x = 1:4, 
           y = c(19, 31, 27, 37), 
           label = c("a", "bc", "b", "c")) +
  annotate("text", x = 1, y = 35,
           label = "ANOVA = <0.001", size = 3)
ggsave("img/barplot_frischmasse.png", 
       width = 5, height = 3)

## Trockengewicht

fit <- lm(trockenmasse ~ versuchsgruppe, data = basi_tbl)

fit %>% 
  anova() %>% 
  parameters()

fit %>% 
  eta_squared()

basi_tbl %$%
  pairwise.t.test(trockenmasse, versuchsgruppe,
                  pool.sd = FALSE, 
                  p.adjust.method = "bonferroni") %>% 
  extract2("p.value") %>% 
  fullPTable() %>% 
  multcompLetters()


## Barplot mit compact letter display und abspeichern

stat_tbl <- basi_tbl %>% 
  group_by(versuchsgruppe) %>% 
  summarise(mean = mean(trockenmasse),
            sd = sd(trockenmasse),
            se = sd/sqrt(n()))

ggplot(stat_tbl, aes(x = versuchsgruppe, y = mean, 
                     fill = versuchsgruppe)) + 
  theme_bw() +
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin = mean-sd, ymax = mean+sd),
                width = 0.2) +
  labs(x = "Versuchsgruppe", y = "Trockenmasse in [g]") +
  theme(legend.position = "none") +
  scale_fill_okabeito() +
  annotate("text", 
           x = 1:4, 
           y = c(1.5, 2.2, 1.9, 2.7), 
           label = c("a", "bc", "b", "c")) +
  annotate("text", x = 1, y = 3,
           label = "ANOVA = <0.001", size = 3)

ggsave("img/barplot_trockenmasse.png", 
       width = 5, height = 3)

##
```


```{r}
basi_time_tbl <- basi_tbl %>% 
  select(versuchsgruppe, t1:t4) %>% 
  pivot_longer(cols = t1:t4,
               values_to = "values",
               names_to = "timepoint") %>% 
  mutate(timepoint = as_factor(timepoint),
         time_num = as.numeric(timepoint))

ggplot(basi_time_tbl, aes(time_num, values, color = versuchsgruppe)) +
  geom_point() +
  stat_summary(fun = "mean", fun.min = "min", fun.max = "max", geom = "line") 
  
ggplot(basi_time_tbl, aes(time_num, values, color = versuchsgruppe)) +
  theme_bw() +
  scale_color_okabeito() +
  geom_jitter(position=position_dodge(0.3), shape = 4) +
  stat_summary(fun.data="mean_sdl", , fun.args = list(mult = 1), 
               geom="pointrange", position=position_dodge(0.3))  +
  stat_summary(fun = "mean", fun.min = "min", fun.max = "max", geom = "line",
               position=position_dodge(0.3)) +
  theme(legend.position = c(0.8, 0.2),
        legend.background = element_rect(color="black", 
                                         size=0.5, linetype="solid"))


lm(values ~ versuchsgruppe + timepoint + versuchsgruppe:timepoint, basi_time_tbl) %>% 
  anova()
 
```
```{r}
lm(values ~ versuchsgruppe + timepoint + versuchsgruppe:timepoint, basi_time_tbl) %>% 
  emmeans(specs = ~ versuchsgruppe | timepoint) %>% 
  contrast(method = "pairwise", adjust = "none") %>% 
  as_tibble %>% 
  select(contrast, timepoint, p.value) %>% 
  mutate(p.value = format.pval(p.value, eps = 0.001, digits = 2)) %>% 
  print(n = Inf)
  
```

```{r}

lm(values ~ versuchsgruppe + timepoint + versuchsgruppe:timepoint, basi_time_tbl) %>% 
  emmeans(specs = ~ versuchsgruppe | timepoint) %>%
  cld(Letters = letters, adjust = "none") 

```


